package com.model;

/**
 * THaoyou generated by MyEclipse Persistence Tools
 */

public class THaoyou implements java.io.Serializable
{

	private Integer id;
	private Integer userId;
	private Integer haoyouId;
	private String shijian;
	
	private TUser haoyou;
	
	
	public Integer getHaoyouId()
	{
		return haoyouId;
	}
	public void setHaoyouId(Integer haoyouId)
	{
		this.haoyouId = haoyouId;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getShijian()
	{
		return shijian;
	}
	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}
	public Integer getUserId()
	{
		return userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}
	public TUser getHaoyou()
	{
		return haoyou;
	}
	public void setHaoyou(TUser haoyou)
	{
		this.haoyou = haoyou;
	}

}