package com.model;

/**
 * TPinglun generated by MyEclipse Persistence Tools
 */

public class TPinglun implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String content;

	private String shjian;

	private Integer bowenId;

	// Constructors

	/** default constructor */
	public TPinglun()
	{
	}

	/** full constructor */
	public TPinglun(String content, String shjian, Integer bowenId)
	{
		this.content = content;
		this.shjian = shjian;
		this.bowenId = bowenId;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public String getShjian()
	{
		return this.shjian;
	}

	public void setShjian(String shjian)
	{
		this.shjian = shjian;
	}

	public Integer getBowenId()
	{
		return this.bowenId;
	}

	public void setBowenId(Integer bowenId)
	{
		this.bowenId = bowenId;
	}

}