package com.model;

import java.util.List;

/**
 * TXiangce generated by MyEclipse Persistence Tools
 */

public class TXiangce implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String name;

	private Integer userId;

	private String del;
	
	private List zhaopianList;

	// Constructors

	/** default constructor */
	public TXiangce()
	{
	}

	/** full constructor */
	public TXiangce(String name, Integer userId, String del)
	{
		this.name = name;
		this.userId = userId;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public List getZhaopianList()
	{
		return zhaopianList;
	}

	public void setZhaopianList(List zhaopianList)
	{
		this.zhaopianList = zhaopianList;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}