package com.model;

/**
 * TZhaopian generated by MyEclipse Persistence Tools
 */

public class TZhaopian implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String title;

	private String fujian;

	private String jieshao;

	private Integer xiangceId;

	private String del;

	// Constructors

	/** default constructor */
	public TZhaopian()
	{
	}

	/** full constructor */
	public TZhaopian(String title, String fujian, String jieshao,
			Integer xiangceId, String del)
	{
		this.title = title;
		this.fujian = fujian;
		this.jieshao = jieshao;
		this.xiangceId = xiangceId;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getTitle()
	{
		return this.title;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}

	public String getFujian()
	{
		return this.fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	public String getJieshao()
	{
		return this.jieshao;
	}

	public void setJieshao(String jieshao)
	{
		this.jieshao = jieshao;
	}

	public Integer getXiangceId()
	{
		return this.xiangceId;
	}

	public void setXiangceId(Integer xiangceId)
	{
		this.xiangceId = xiangceId;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}